// Code generated by entc, DO NOT EDIT.

package userwallet

import (
	"time"
)

const (
	// Label holds the string label denoting the userwallet type in the database.
	Label = "user_wallet"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldBalance holds the string denoting the balance field in the database.
	FieldBalance = "balance"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeUserWalletCards holds the string denoting the user_wallet_cards edge name in mutations.
	EdgeUserWalletCards = "user_wallet_cards"
	// Table holds the table name of the userwallet in the database.
	Table = "user_wallets"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_wallets"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// UserWalletCardsTable is the table that holds the user_wallet_cards relation/edge.
	UserWalletCardsTable = "user_cards"
	// UserWalletCardsInverseTable is the table name for the UserCard entity.
	// It exists in this package in order to avoid circular dependency with the "usercard" package.
	UserWalletCardsInverseTable = "user_cards"
	// UserWalletCardsColumn is the table column denoting the user_wallet_cards relation/edge.
	UserWalletCardsColumn = "wallet_id"
)

// Columns holds all SQL columns for userwallet fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldBalance,
	FieldUserID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
