// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/indrasaputra/spenmo/internal/repository/model/ent/schema"
	"github.com/indrasaputra/spenmo/internal/repository/model/ent/user"
	"github.com/indrasaputra/spenmo/internal/repository/model/ent/usercard"
	"github.com/indrasaputra/spenmo/internal/repository/model/ent/userwallet"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	usercardMixin := schema.UserCard{}.Mixin()
	usercardMixinFields0 := usercardMixin[0].Fields()
	_ = usercardMixinFields0
	usercardFields := schema.UserCard{}.Fields()
	_ = usercardFields
	// usercardDescCreatedAt is the schema descriptor for created_at field.
	usercardDescCreatedAt := usercardMixinFields0[0].Descriptor()
	// usercard.DefaultCreatedAt holds the default value on creation for the created_at field.
	usercard.DefaultCreatedAt = usercardDescCreatedAt.Default.(func() time.Time)
	// usercardDescUpdatedAt is the schema descriptor for updated_at field.
	usercardDescUpdatedAt := usercardMixinFields0[1].Descriptor()
	// usercard.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	usercard.DefaultUpdatedAt = usercardDescUpdatedAt.Default.(func() time.Time)
	// usercard.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	usercard.UpdateDefaultUpdatedAt = usercardDescUpdatedAt.UpdateDefault.(func() time.Time)
	userwalletMixin := schema.UserWallet{}.Mixin()
	userwalletMixinFields0 := userwalletMixin[0].Fields()
	_ = userwalletMixinFields0
	userwalletFields := schema.UserWallet{}.Fields()
	_ = userwalletFields
	// userwalletDescCreatedAt is the schema descriptor for created_at field.
	userwalletDescCreatedAt := userwalletMixinFields0[0].Descriptor()
	// userwallet.DefaultCreatedAt holds the default value on creation for the created_at field.
	userwallet.DefaultCreatedAt = userwalletDescCreatedAt.Default.(func() time.Time)
	// userwalletDescUpdatedAt is the schema descriptor for updated_at field.
	userwalletDescUpdatedAt := userwalletMixinFields0[1].Descriptor()
	// userwallet.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userwallet.DefaultUpdatedAt = userwalletDescUpdatedAt.Default.(func() time.Time)
	// userwallet.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userwallet.UpdateDefaultUpdatedAt = userwalletDescUpdatedAt.UpdateDefault.(func() time.Time)
}
